config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('godtk/', include('godtk.urls')),
    path('accounts/',include('accounts.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

godtk/urls.py
from django.urls import path
from . import views

app_name = 'godtk'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:godtk_pk>/', views.detail, name='detail'),
    path('<int:godtk_pk>/delete/', views.delete, name='delete'),
    path('<int:godtk_pk>/update/', views.update, name='update'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    path('search/', views.search, name='search'),
]

godtk/models.py
from django.db import models
from django.conf import settings

class Hashtag(models.Model):
  tag = models.TextField(unique=True)

  # 객체 표현 방식
  def __str__(self):
    return self.tag 

class Godtk(models.Model):
  company_name = models.CharField(max_length=40, blank=True)   # 업체이름
  event_title = models.CharField(max_length=40)                # 행사 타이틀
  start_date = models.TextField(null=True, blank=True)         # 행사 시작 날짜
  end_date = models.TextField(null=True, blank=True)           # 행사 끝나는 날짜
  content = models.TextField(null=True, blank=True)            # 행사 소개
  event_url = models.TextField(null=True, blank=True)          # 행사 url
  img_path = models.ImageField(blank=True)                     # 행사 이미지
  tag = models.TextField(null=True, blank=True)                # 태그

  hashtag = models.ManyToManyField(Hashtag, blank=True)        # 해시태그

  def __str__(self):
    return f'[{self.pk}] {self.event_title}|{self.content}'

godtk/forms.py
from django import forms
from .models import Godtk

class GodtkForm(forms.ModelForm):
    #메타데이터 :  데이터의 데이터
    #ex) 사진 한장 (촬영장비이름, 촬영환경 등)
    company_name = forms.CharField(
        label='업체이름',
        widget=forms.TextInput(
            attrs={
                'class':'company_name',
                'placeholder':'업체이름'
            }
        )
    )
    event_title = forms.CharField(
        label='이벤트이름',
        widget=forms.TextInput(
            attrs={
                'class':'event_title',
                'placeholder':'이벤트이름'
            }
        )
    )
    start_date = forms.CharField(
        label='이벤트시작날짜',
        widget=forms.TextInput(
            attrs={
                'class':'start_date',
                'placeholder':'이벤트시작날짜'
            }
        )
    )
    end_date = forms.CharField(
        label='이벤트끝나는날짜',
        widget=forms.TextInput(
            attrs={
                'class':'end_date',
                'placeholder':'이벤트끝나는날짜'
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class':'content',
                'placeholder':'내용입력',
                'rows':5,
                'cols':30
            }
        )
    )
    tag = forms.CharField(
        label='해시태그',
        widget=forms.TextInput(
            attrs={
                'class':'hashtag',
                'placeholder':'해시태그',
                'rows':5,
                'cols':30
            }
        )
    )
    event_url = forms.CharField(
        label='event_url',
        widget=forms.TextInput(
            attrs={
                'class':'event_url',
                'placeholder':'event_url'
            }
        )
    )
    img_path = forms.ImageField(label='img_path', required=False)

    class Meta:
        model = Godtk
        #fields = '__all__' #전체가져오기
        fields = ('event_title','company_name','start_date','end_date','tag','content','event_url','img_path') #선택해서 데이터 가져오기

godtk/views.py
import hashlib
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from IPython import embed
from .models import Hashtag
from .models import Godtk
from .forms import GodtkForm
from django.http import JsonResponse, HttpResponseBadRequest
from django.db.models import Q

def index(request):
    godtk = Godtk.objects.all()[::-1]
    context = {'godtk' : godtk}
    return render(request, 'godtk/index.html', context)

def detail(request, godtk_pk):
    godtk = get_object_or_404(Godtk, pk=godtk_pk)

    context = {
        'godtk': godtk,
    }
    return render(request, 'godtk/detail.html', context)

def hashtag(request, hash_pk):
  # 해시태그 가져오기
  hashtag = get_object_or_404(Hashtag, pk=hash_pk)
  # 해당 해시태그를 참조하는 게시글들 가져오기
  godtk = hashtag.godtk_set.order_by('-pk')
  context = {
    'hashtag' : hashtag,
    'godtk' : godtk,
  }
  return render(request, 'godtk/hashtag.html', context)

def search(request):
    # 사용자가 입력한 검색어 가져오기
    query = request.GET.get('query')
    # DB에서 query가 포함된 제목을 가진 artice 가져오기 (LIKE)
    # __contatins : 지정한 문자열 포함하는 자료검색
    # __icontains : 지정한 문자열 포함하는 자료검색(대소문자 구별 X)
    godtk = Godtk.objects.filter(event_title__icontains=query)

    # context로 전달
    context = {'godtk': godtk}
    return render(request, 'godtk/search.html',context)

def create(request):
    if request.user.is_authenticated: #작성자가 같은경우만
        if request.method == 'POST':
            # Binding 과정
            # 폼 인스턴스를 생성하고, 전달받은 데이터를 채운다.
            # 인스턴스에 데이터를 채워서, 유효성 검증을 진행한다. (그래서 변수에 담음)
            form = GodtkForm(request.POST, request.FILES)
            # embed()
            if form.is_valid():
                godtk = form.save(commit=False)
                godtk.user = request.user
                godtk.save()

                # hashtag
                # 게시글 내용을 split해서 리스트로 만듦
                for word in godtk.tag.split():
                    # word가 '#'으로 시작할 경우 해시태그 등록
                    if word.startswith('#'):
                        hashtag, created = Hashtag.objects.get_or_create(tag=word)
                        godtk.hashtag.add(hashtag)


            return redirect('godtk:detail', godtk.pk)
        else:
            form = GodtkForm()

        # form으로 전달받는 형태가 2가지
        # 1. GET 요청 -> 비어있는 폼 전달
        # 2. 유효성 검증 실패 -> 에러 메세지를 포함한 채로 폼 전달
        context = {'form':form}
        return render(request,'godtk/form.html', context)
    else:
        return redirect('godtk:index')

def update(request, godtk_pk):
    godtk = get_object_or_404(Godtk, pk=godtk_pk)
    if request.user.is_authenticated: #작성자가 같은경우만
        if request.method == "POST":
            form = GodtkForm(request.POST, request.FILES, instance=godtk)
            if form.is_valid():
                godtk = form.save()
                # hashtag
                godtk.hashtag.clear()
                for word in godtk.content.split():
                    if word.startswith('#'):
                        hashtag, create = Hashtag.objects.get_or_create(content=word)
                        godtk.hashtag.add(hashtag)
                return redirect('godtk:detail', godtk.pk)
        else:
            form = GodtkForm(instance=godtk)       
    else:
        return redirect('godtk/index')   

    # context로 전달되는 2가지 form 형식
    # 1. GET -> 초기값을 폼에 넣어서 사용자에게 던져줌
    # 2. POST -> is_valid가 False가 리턴됬을 때, 오류 메세지를 포함해서 동작한다.
    context = {
        'form':form,
        'godtk':godtk
    }
    return render(request, 'godtk/form.html', context)

@require_POST
def delete(request, godtk_pk):    
    if request.user.is_authenticated:#사용자가 로그인 되어 있는지
        godtk = get_object_or_404(Godtk,pk=godtk_pk) #삭제할 게시글
        godtk.delete()

    return redirect('godtk:index')

config/templates/godtk/_article.html
{% load make_link %}

<div class="col-12 col-md-6 mb-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          이벤트: {{godtk.event_title}}</h5>
        <p class="card-text">
       
        <br>
          내용: {{godtk.content}}
        </br>
     
          해시태그: {{godtk|hashtag_link|safe}}
        <br>
         기간: {{godtk.start_date}} ~ {{godtk.end_date}}
        <br>

        </p>
       
       <a href="{% url 'godtk:detail' godtk.pk %}" class="btn btn-primary">상세보기</a>
      </div>
    </div>
</div>

config/templates/godtk/detail copy.html
{% extends 'base.html' %}
{% load make_link %}
{% load bootstrap4 %}
{% block body %}
  <br>
  <h1>DETAIL</h1>
  <hr>
<p>이벤트 : {{ godtk.event_title }}</p>
<P>업체 : {{ godtk.company_name }}</p>
<P>행사 시작 날짜: {{ godtk.start_date }} </p>
<P>행사 끝나는 날짜 : {{ godtk.end_date }}</p>
<P>행사 소개 : {{ godtk.content }}</p>
<P>URL 주소 : {{ godtk.event_url }}</p>
<P>이미지 : {{ godtk.img_path }}</p>
{% comment %} <p>글 내용 : {{ article.content }}</p> {% endcomment %}
<p>해시태그:{{godtk|hashtag_link|safe }}</p>
<hr>
<a href="{% url 'godtk:index' %}">[BACK]</a>
{% if user.is_authenticated %}
<a href="{% url 'godtk:update' godtk.pk %}">[UPDATE]<a>
<form action="{% url 'godtk:delete' godtk.pk %}" method="POST">
{% csrf_token %}<button type="submit" >[DELETE]</button>
</form>
<hr>
{% endif %}
{% endblock %}

config/templates/godtk/detail.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href={% static 'css/detail.css' %}>
{% load make_link %}
{% load bootstrap4 %}

{% block body %}

  <br>
  <h1>DETAIL</h1>
  <hr>
  <img src="{% static 'godtk/images/captuer.png' %}" alt="no_image" style="width:250px;">
<p>이벤트 : {{ godtk.event_title }}</p>
<P>업체 : {{ godtk.company_name }}</p>
<P>행사 시작 날짜: {{ godtk.start_date }} </p>
<P>행사 끝나는 날짜 : {{ godtk.end_date }}</p>
<P>행사 소개 : {{ godtk.content }}</p>
<P>URL 주소 : {{ godtk.event_url }}</p>
{% if godtk.img_path %}
  <P>이미지 : <img src="{{ godtk.img_path.url }}"</p>
{% endif %}
{% comment %} <p>글 내용 : {{ article.content }}</p> {% endcomment %}
<p>해시태그:{{godtk|hashtag_link|safe }}</p>
<hr>


<a href="{% url 'godtk:index' %}">[BACK]</a>
{% if user.is_authenticated %}
<a href="{% url 'godtk:update' godtk.pk %}">[UPDATE]<a>
<form action="{% url 'godtk:delete' godtk.pk %}" method="POST">
{% csrf_token %}<button type="submit" >[DELETE]</button>
</form>
<hr>
{% endif %}
{% endblock %}

config/templates/godtk/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
<h1>CREATE</h1>
{% else %}
<h1>UPDATE</h1>
{% endif %}
<hr>
<!--
  action 값이 공백일 경우, 현재 위치하고 있는 주소로 요청을 보낸다. 폼을 던져주는 경로,
  DB에 저장하는 경로가 동일하다면 공백으로 해도 정상적으로 동작한다.
-->
<form action="" method="POST" enctype="multipart/form-data">
  <!-- POST 요청할 때 반드시 설정 -->
  {% csrf_token %}
  {% bootstrap_form form layout='inline' %}
  {% comment %} {{ form.as_p }} {% endcomment %}

  {% comment %} <input type="submit"> {% endcomment %}
  <div class="text-center">
    {% buttons submit='제출' reset="초기화" %}{% endbuttons %}
  </div>
</form>
<hr>
{% if request.resolver_match.url_name == 'create' %}
<a href="{% url 'godtk:index' %}">[BACK]</a>
{% else %}
<a href="{% url 'godtk:detail' godtk.pk %}">[BACK]</a>
{% endif %}

{% endblock %}

config/templates/godtk/hashtag.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ hashtag.tag }} 게시글 모아보기 </h1>
<h4>{{ godtk|length }}개의 글이 있습니다.</h4>
<hr>
<div class="row">
{% for godtk in godtk %}
  {% include 'godtk/_article.html' %}
{% endfor %}
{% endblock body %}
</div>

config/templates/godtk/index.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-center">GodTK</h1>

{% if user.is_authenticated %}
  <a href="{% url 'godtk:create' %}">[관리자] 생성</a>
{% endif %}

<hr>

<h1>TEST</h1>
<form class="mb-4" action="{% url 'godtk:search' %}">
    <div class="form-row justify-content-center">
      <div class="mb-2 col-12 col-sm-9 col-md-10">
        <input type="text" class="form-control" name="query" placeholder="제목을 입력해주세요">
      </div>
      <div class="col-12 col-sm-3 col-md-2">
        <input type="submit" class="form-control btn btn-success" value="검색">
      </div>
    </div>
</form>

<hr>
<div class="row">
  {% for godtk in godtk %}
  <!-- 모듈화 시켜둔 article 템플릿 가져오기 -->
  {% include 'godtk/_article.html' %}
  {% endfor %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if godtk.has_previous %}
    <li class="page-item ">
      <a class="page-link" href="{% url 'godtk:index' %}?page={{godtk.previous_page_number}}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    {% endif %}
    <!--페이지버튼-->
    {% for num in godtk.paginator.page_range %}
    <li class="page-item" {% if num == godtk.number %}active{% endif %}><a class="page-link" href="{% url 'godtk:index' %}?page={{ num }}">{{ num }}</a></li>
    {% endfor%}

    {% if godtk.has_next %}
    <li class="has_next">
      <a class="page-link" href="{% url 'godtk:index' %}?page={{godtk.next_page_number}}">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endblock body %}

config/templates/godtk/search.html
{% extends 'base.html' %}

{% block body %}
<h1>검색결과</h1><br>
  <form class="mb-4" action="{% url 'godtk:search' %}">
    <div class="form-row justify-content-center">
      <div class="mb-2 col-12 col-sm-9 col-md-10">
        <input type="text" class="form-control" name="query" placeholder="제목을 입력해주세요">
      </div>
      <div class="col-12 col-sm-3 col-md-2">
        <input type="submit" class="form-control btn btn-success" value="검색">
      </div>
    </div>
  </form>

 <ul class="list-group">
 {% for godtk in godtk %}
  <a href={% url 'godtk:detail' godtk.pk %} class="mb-2">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    [{{ forloop.counter }}]{{godtk.event_title}}
  </li>
  </a>
  {% endfor %}
</ul>
{% endblock body %}